"""``write-env`` subcommand.

Validate + write ``.env`` from a preset template.

Preset templates live in ``src/skillsmith/install/presets/<name>.yaml``.
Each preset has fixed runner URLs (Ollama 11434, LM Studio 1234,
FastFlowLM 52625).  The ``--port`` flag records the skillsmith
service port (default 8000) for use by ``wire-harness``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

from skillsmith.install import state as install_state

SCHEMA_VERSION = 1
DEFAULT_PORT = 8000

VALID_PRESETS = frozenset({"cpu", "apple-silicon", "nvidia", "strix-point"})

# Keys the user is allowed to override via --overrides.
_KNOWN_KEYS = frozenset(
    {
        "LADYBUG_DB_PATH",
        "DUCKDB_PATH",
        "RUNTIME_EMBED_BASE_URL",
        "RUNTIME_EMBEDDING_MODEL",
        "LM_STUDIO_BASE_URL",
        "AUTHORING_EMBED_BASE_URL",
        "AUTHORING_MODEL",
        "CRITIC_MODEL",
        "AUTHORING_EMBEDDING_MODEL",
        "DEDUP_HARD_THRESHOLD",
        "DEDUP_SOFT_THRESHOLD",
        "BOUNCE_BUDGET",
        "LOG_LEVEL",
    }
)

# Sentinel comment marking a CLI-generated .env
_SENTINEL = "# Generated by skillsmith install write-env"


def _load_preset(name: str) -> dict[str, str]:
    """Load a preset YAML from the presets package directory."""
    presets_dir = Path(__file__).resolve().parent.parent / "presets"
    preset_file = presets_dir / f"{name}.yaml"
    if not preset_file.exists():
        print(f"ERROR: Unknown preset '{name}'", file=sys.stderr)
        print(f"CAUSE: No preset template at {preset_file}", file=sys.stderr)
        print(f"FIX:   Use one of: {', '.join(sorted(VALID_PRESETS))}", file=sys.stderr)
        raise SystemExit(1)
    data = yaml.safe_load(preset_file.read_text())
    return data.get("defaults", {})


def _parse_overrides(override_args: list[str] | None) -> dict[str, str]:
    """Parse KEY=VALUE override pairs, rejecting unknown keys."""
    if not override_args:
        return {}
    overrides: dict[str, str] = {}
    for item in override_args:
        if "=" not in item:
            print(f"ERROR: Invalid override format: '{item}'", file=sys.stderr)
            print("CAUSE: Overrides must be KEY=VALUE pairs.", file=sys.stderr)
            print("FIX:   Use --overrides KEY=VALUE KEY=VALUE ...", file=sys.stderr)
            raise SystemExit(1)
        key, _, value = item.partition("=")
        if key not in _KNOWN_KEYS:
            print(f"ERROR: Unknown override key: '{key}'", file=sys.stderr)
            print("CAUSE: Typo or unsupported key.", file=sys.stderr)
            print(f"FIX:   Valid keys: {', '.join(sorted(_KNOWN_KEYS))}", file=sys.stderr)
            raise SystemExit(1)
        overrides[key] = value
    return overrides


def _render_env(values: dict[str, str], preset: str, port: int) -> str:
    """Render .env file content from the merged values dict."""
    lines = [
        _SENTINEL,
        f"# Preset: {preset}, Port: {port}",
        "",
    ]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def write_env(
    preset: str,
    port: int = DEFAULT_PORT,
    overrides: dict[str, str] | None = None,
    force: bool = False,
    root: Path | None = None,
) -> dict[str, Any]:
    """Generate and write the .env file. Returns the contract-shaped result."""
    # `.env` is now user-scoped (lives in the XDG config dir) so a single
    # Skillsmith service can serve every repo the user opens. The legacy
    # per-repo location is no longer written; if one exists the user must
    # remove it manually (it's now ignored at runtime).
    env_path = install_state.env_path()

    # Refuse to overwrite hand-edited .env without --force
    if env_path.exists():
        existing = env_path.read_text()
        if _SENTINEL not in existing and not force:
            print(
                "ERROR: Cannot write .env: file exists and was not produced by a prior install",
                file=sys.stderr,
            )
            print(
                f"CAUSE: A hand-edited or third-party .env is present at {env_path}.",
                file=sys.stderr,
            )
            print(
                "FIX:   Either move the existing file aside, or run `write-env --force` to overwrite",
                file=sys.stderr,
            )
            raise SystemExit(1)

    defaults = _load_preset(preset)

    # Apply overrides on top of preset defaults
    values: dict[str, str] = dict(defaults)

    # Apply overrides
    if overrides:
        values.update(overrides)

    content = _render_env(values, preset, port)
    install_state._atomic_write(env_path, content)  # pyright: ignore[reportPrivateUsage]
    # `.env` may carry tokens or runtime URLs; restrict to owner-only on
    # POSIX. Windows ignores chmod and falls back to NTFS ACL defaults.
    import os as _os

    with __import__("contextlib").suppress(NotImplementedError, OSError):
        _os.chmod(env_path, 0o600)

    return {
        "schema_version": SCHEMA_VERSION,
        "env_path": str(env_path),
        "preset": preset,
        "port": port,
        "values_written": values,
    }


# ---------------------------------------------------------------------------
# Subcommand interface
# ---------------------------------------------------------------------------


def add_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:  # pyright: ignore[reportPrivateUsage]
    p: argparse.ArgumentParser = subparsers.add_parser(
        "write-env",
        help="Validate + write .env from a preset template.",
    )
    p.add_argument(
        "--preset",
        required=True,
        choices=sorted(VALID_PRESETS),
        help="Preset name to use as the base template.",
    )
    p.add_argument(
        "--port",
        type=int,
        default=DEFAULT_PORT,
        help=f"API port (default: {DEFAULT_PORT}).",
    )
    p.add_argument(
        "--overrides",
        nargs="*",
        metavar="KEY=VALUE",
        help="Override specific env values (e.g. AUTHORING_MODEL=qwen3.5:1.7b).",
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing hand-edited .env file.",
    )
    p.set_defaults(func=run)


def run(args: argparse.Namespace) -> int:
    """Execute the write-env subcommand.

    Always re-renders. The user may pass a different ``--port`` or
    ``--overrides`` on a re-run; caching the previous output would silently
    ignore them.
    """
    st = install_state.load_state()
    overrides = _parse_overrides(args.overrides)
    result = write_env(
        preset=args.preset,
        port=args.port,
        overrides=overrides,
        force=args.force,
    )

    fp, digest = install_state.save_output_file(result, "write-env.json")
    install_state.record_step(
        st,
        "write-env",
        extra={
            "output_digest": digest,
            "output_path": str(fp),
            "env_path": result["env_path"],
            "port": result["port"],
        },
    )
    # Also update top-level state fields
    st["env_path"] = result["env_path"]
    st["port"] = result["port"]
    install_state.save_state(st)

    json.dump(result, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0
