"""Unit tests for the ``uninstall`` subcommand."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from skillsmith.install import state as install_state
from skillsmith.install.subcommands.uninstall import uninstall
from skillsmith.install.subcommands.wire_harness import SENTINEL_BEGIN, SENTINEL_END


@pytest.fixture()
def repo_root(tmp_path: Path) -> Path:
    (tmp_path / "pyproject.toml").write_text("")
    return tmp_path


def _setup_installed(root: Path) -> None:
    """Set up a full install state for uninstall to clean."""
    import hashlib

    # .env (user-scope)
    env_path = install_state.env_path()
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text("# Generated by skillsmith install write-env\nKEY=val\n")

    # CLAUDE.md with sentinel block. The recorded content_sha256 must match
    # what uninstall extracts via _extract_sentinel_content(...).strip(),
    # otherwise the tamper-detection check refuses removal (by design).
    inner = "Skill API content"
    claude = root / "CLAUDE.md"
    claude.write_text(f"# My Project\n\n{SENTINEL_BEGIN}\n{inner}\n{SENTINEL_END}\n")
    inner_sha = hashlib.sha256(inner.encode()).hexdigest()

    # State (user-scope)
    st = install_state.load_state(root)
    st["harness_files_written"] = [
        {
            "path": str(claude),
            "harness": "claude-code",
            "repo_root": str(root),
            "action": "injected_block",
            "sentinel_begin": SENTINEL_BEGIN,
            "sentinel_end": SENTINEL_END,
            "content_sha256": inner_sha,
        }
    ]
    st["completed_steps"] = [
        {"step": "detect"},
        {"step": "wire-harness"},
    ]
    install_state.save_state(st, root)

    # User-scope corpus dir (the new "data dir" location)
    corpus = install_state.corpus_dir()
    corpus.mkdir(parents=True, exist_ok=True)
    (corpus / "skills.duck").write_text("fake")


# ---------------------------------------------------------------------------
# Basic uninstall
# ---------------------------------------------------------------------------


class TestUninstall:
    def test_removes_env(self, repo_root: Path) -> None:
        _setup_installed(repo_root)
        env_path = install_state.env_path()
        result = uninstall(root=repo_root)
        assert not env_path.exists()
        assert any(f["path"].endswith(".env") for f in result["files_removed"])

    def test_removes_sentinel_block(self, repo_root: Path) -> None:
        _setup_installed(repo_root)
        result = uninstall(root=repo_root)
        claude = repo_root / "CLAUDE.md"
        if claude.exists():
            content = claude.read_text()
            assert SENTINEL_BEGIN not in content
            assert "# My Project" in content
        else:
            # File deleted because only our content was there
            pass
        assert any(
            "sentinel" in f.get("action", "") or "deleted" in f.get("action", "")
            for f in result["files_modified"] + result["files_removed"]
        )

    def test_removes_state_directory(self, repo_root: Path) -> None:
        _setup_installed(repo_root)
        state_dir = install_state.state_dir()
        uninstall(root=repo_root)
        assert not state_dir.exists()

    def test_preserves_data_by_default(self, repo_root: Path) -> None:
        _setup_installed(repo_root)
        corpus = install_state.corpus_dir()
        result = uninstall(root=repo_root)
        assert corpus.exists()
        assert len(result["data_kept"]) == 1

    def test_removes_data_when_requested(self, repo_root: Path) -> None:
        _setup_installed(repo_root)
        corpus = install_state.corpus_dir()
        result = uninstall(remove_data=True, root=repo_root)
        assert not corpus.exists()
        assert result["data_kept"] == []


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestEdgeCases:
    def test_no_state_file(self, repo_root: Path) -> None:
        """Uninstall on a clean repo should not error."""
        result = uninstall(root=repo_root)
        assert result["schema_version"] == 1
        assert result["warnings"] == []

    def test_missing_harness_file_warns(self, repo_root: Path) -> None:
        st = install_state.load_state(repo_root)
        # Use a path that ends in a known harness target basename so it
        # passes the suffix-allowlist check; the warning should then
        # surface the "not found" condition.
        st["harness_files_written"] = [
            {
                "path": str(repo_root / "CLAUDE.md"),
                "action": "injected_block",
                "sentinel_begin": SENTINEL_BEGIN,
                "sentinel_end": SENTINEL_END,
                "harness": "claude-code",
                "repo_root": str(repo_root),
            }
        ]
        install_state.save_state(st, repo_root)
        result = uninstall(root=repo_root)
        assert any("not found" in w for w in result["warnings"])

    def test_dedicated_file_deleted(self, repo_root: Path) -> None:
        """Dedicated files (e.g., .cursor/rules/skillsmith.mdc) are deleted entirely."""
        mdc = repo_root / ".cursor" / "rules" / "skillsmith.mdc"
        mdc.parent.mkdir(parents=True)
        mdc.write_text("our content")
        st = install_state.load_state(repo_root)
        st["harness_files_written"] = [
            {
                "path": str(mdc),
                "action": "wrote_new_file",
                "sentinel_begin": None,
                "sentinel_end": None,
                "content_sha256": "abc",
            }
        ]
        install_state.save_state(st, repo_root)
        uninstall(root=repo_root)
        assert not mdc.exists()

    def test_force_removes_without_sentinels(self, repo_root: Path) -> None:
        harness_file = repo_root / "CLAUDE.md"
        harness_file.write_text("Content without sentinels\n")
        st = install_state.load_state(repo_root)
        st["harness_files_written"] = [
            {
                "path": str(harness_file),
                "action": "injected_block",
                "sentinel_begin": SENTINEL_BEGIN,
                "sentinel_end": SENTINEL_END,
            }
        ]
        install_state.save_state(st, repo_root)
        uninstall(force=True, root=repo_root)
        assert not harness_file.exists()


# ---------------------------------------------------------------------------
# Continue.dev cleanup
# ---------------------------------------------------------------------------


class TestContinueCleanup:
    def test_cleans_continuerc(self, repo_root: Path) -> None:
        config: dict[str, Any] = {
            "models": [{"title": "GPT-4"}],
            "customCommands": [
                {"name": "skill", "description": "test", "prompt": "test"},
                {"name": "other", "description": "keep", "prompt": "keep"},
            ],
            "systemMessage": "User msg\n\n<!-- skillsmith:begin -->\nour injection\n<!-- skillsmith:end -->",
            "_skillsmith_install_marker": {"managed_by": "skillsmith install", "added_paths": []},
        }
        (repo_root / ".continuerc.json").write_text(json.dumps(config))
        install_state.save_state(install_state.load_state(repo_root), repo_root)
        uninstall(root=repo_root)
        result_config = json.loads((repo_root / ".continuerc.json").read_text())
        assert "skill" not in [c["name"] for c in result_config.get("customCommands", [])]
        assert "_skillsmith_install_marker" not in result_config
        assert result_config["models"] == [{"title": "GPT-4"}]


# ---------------------------------------------------------------------------
# Tamper detection
# ---------------------------------------------------------------------------


class TestTamperDetection:
    def test_modified_sentinel_block_skipped_without_force(self, repo_root: Path) -> None:
        """If user edited inside the sentinels, refuse to clobber without --force."""
        import hashlib

        claude = repo_root / "CLAUDE.md"
        # Recorded sha matches "original content"; live file has different inner.
        original_inner = "original content"
        claude.write_text(f"# Project\n\n{SENTINEL_BEGIN}\nuser edited this\n{SENTINEL_END}\n")
        recorded_sha = hashlib.sha256(original_inner.encode()).hexdigest()
        st = install_state.load_state(repo_root)
        st["harness_files_written"] = [
            {
                "path": str(claude),
                "action": "injected_block",
                "sentinel_begin": SENTINEL_BEGIN,
                "sentinel_end": SENTINEL_END,
                "content_sha256": recorded_sha,
            }
        ]
        install_state.save_state(st, repo_root)
        result = uninstall(root=repo_root)
        # Block was preserved
        assert SENTINEL_BEGIN in claude.read_text()
        assert any("Tampered" in w or "sha256 mismatch" in w for w in result["warnings"])

    def test_tampered_block_removed_with_force(self, repo_root: Path) -> None:
        import hashlib

        claude = repo_root / "CLAUDE.md"
        original_inner = "original content"
        claude.write_text(f"# Project\n\n{SENTINEL_BEGIN}\nuser edited\n{SENTINEL_END}\n")
        recorded_sha = hashlib.sha256(original_inner.encode()).hexdigest()
        st = install_state.load_state(repo_root)
        st["harness_files_written"] = [
            {
                "path": str(claude),
                "action": "injected_block",
                "sentinel_begin": SENTINEL_BEGIN,
                "sentinel_end": SENTINEL_END,
                "content_sha256": recorded_sha,
            }
        ]
        install_state.save_state(st, repo_root)
        uninstall(force=True, root=repo_root)
        if claude.exists():
            assert SENTINEL_BEGIN not in claude.read_text()


# ---------------------------------------------------------------------------
# MCP config cleanup
# ---------------------------------------------------------------------------


class TestMcpCleanup:
    def test_cursor_mcp_entry_removed(self, repo_root: Path) -> None:
        cursor = repo_root / ".cursor" / "mcp.json"
        cursor.parent.mkdir(parents=True)
        cursor.write_text(
            json.dumps({"mcpServers": {"skillsmith": {"command": "x"}, "other": {"command": "y"}}})
        )
        uninstall(root=repo_root)
        cfg = json.loads(cursor.read_text())
        assert "skillsmith" not in cfg["mcpServers"]
        assert "other" in cfg["mcpServers"]

    def test_cursor_mcp_file_deleted_when_empty(self, repo_root: Path) -> None:
        cursor = repo_root / ".cursor" / "mcp.json"
        cursor.parent.mkdir(parents=True)
        cursor.write_text(json.dumps({"mcpServers": {"skillsmith": {"command": "x"}}}))
        uninstall(root=repo_root)
        assert not cursor.exists()

    def test_continuerc_mcp_servers_removed(self, repo_root: Path) -> None:
        config: dict[str, Any] = {
            "models": [{"title": "GPT-4"}],
            "mcpServers": {"skillsmith": {"command": "x"}, "other": {"command": "y"}},
        }
        (repo_root / ".continuerc.json").write_text(json.dumps(config))
        uninstall(root=repo_root)
        cfg = json.loads((repo_root / ".continuerc.json").read_text())
        assert "skillsmith" not in cfg.get("mcpServers", {})
        assert "other" in cfg["mcpServers"]


# ---------------------------------------------------------------------------
# Output schema
# ---------------------------------------------------------------------------


class TestOutputSchema:
    def test_required_keys(self, repo_root: Path) -> None:
        result = uninstall(root=repo_root)
        assert result["schema_version"] == 1
        assert "files_modified" in result
        assert "files_removed" in result
        assert "data_kept" in result
        assert "warnings" in result
